### ISSUE TITLE
Add support for projects without issues tab.

### ISSUE THREAD

**Issue by makorne** [KaiserKarel/issue-rs#6]
For example: [https://github.com/KaiserKarel/prosit](url) does not have issues tab.

This project has no working example, and its code snippets create non-working code.

As it does not have issues tab, I wrote to the owner in comments [https://github.com/KaiserKarel/prosit/commit/9d04e8edeb1fae028cd2fad1c446d6b6f6b52ddf](url) and hope some day he reads and may be can create a working example for his crate.
But looks like it will be in the next thousand years. 

It  would be great to create for it something like: 
```
#[issue::track(url="https://github.com/KaiserKarel/prosit/commit/9d04e8edeb1fae028cd2fad1c446d6b6f6b52dd")]
type Result<T> = core::result::Result<T, ()>; 
```
And some day in future, my grandchildren on Mars will be shocked:  "a warning will be emitted during compile time."

It is an issue with a joke, Karel!
Please, create a working example for prosit!!

Cheers!

**Comment by KaiserKarel** [comment]
So if I am understanding you correctly, you'd like to be able to refer to specific commits? What data would we then fetch?

`track` currently parses the url, obtains the issue number and then calls the api.github.com to obtain the information. Forks do not have issue tabs, so I am unsure if the API exposes that info.

Prosit does create working code, we're using it in a project right now. Although it is meant as an experiment with the possibility of becoming a new library later on. I can see if I can add an issue tab to prosit to help you out there.

--- EDIT ---
Apparently forks can have issue tabs, I had simply not enabled it.

**Comment by makorne** [comment]
Looks like enabling the issue tab is enough!

I am sure your code works, but I cannot do it with code snippets from the first page of prosit.
Please add a working example project, just of code snipets from the first page.

**Comment by KaiserKarel** [comment]
Will do. :) 

Closing this issue then.
